
-- DropIndex
DROP INDEX "bas_sites_org_id_name_key";

-- AlterTable
ALTER TABLE "bas_sites" ADD COLUMN     "project_id" BIGINT;

-- AlterTable
ALTER TABLE "bas_stations" ADD COLUMN     "connection_mode" TEXT NOT NULL DEFAULT 'via_parent';

-- CreateTable
CREATE TABLE "bas_projects" (
    "project_id" BIGSERIAL NOT NULL,
    "org_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bas_projects_pkey" PRIMARY KEY ("project_id")
);

-- CreateTable
CREATE TABLE "bas_station_credentials" (
    "station_id" BIGINT NOT NULL,
    "username" TEXT NOT NULL,
    "password_ciphertext" TEXT NOT NULL,
    "key_version" INTEGER NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" UUID,

    CONSTRAINT "bas_station_credentials_pkey" PRIMARY KEY ("station_id")
);

-- CreateIndex
CREATE INDEX "bas_projects_org_id_idx" ON "bas_projects"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "bas_projects_org_id_name_key" ON "bas_projects"("org_id", "name");

-- CreateIndex
CREATE INDEX "bas_station_credentials_updated_by_idx" ON "bas_station_credentials"("updated_by");

-- CreateIndex
CREATE INDEX "bas_sites_project_id_idx" ON "bas_sites"("project_id");

-- CreateIndex
CREATE UNIQUE INDEX "bas_sites_project_id_name_key" ON "bas_sites"("project_id", "name");

-- AddForeignKey
ALTER TABLE "bas_projects" ADD CONSTRAINT "bas_projects_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "bas_orgs"("org_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bas_sites" ADD CONSTRAINT "bas_sites_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "bas_projects"("project_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bas_station_credentials" ADD CONSTRAINT "bas_station_credentials_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bas_stations"("station_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bas_station_credentials" ADD CONSTRAINT "bas_station_credentials_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;



-- =============================================================================
-- Everything above this line was generated by the Prisma migration engine.
-- Everything below it was written by hand, because Prisma cannot express it.
--
-- ONE line above was edited, and only one. Prisma emits
--
--     ALTER TABLE "bas_sites" ADD COLUMN "project_id" BIGINT NOT NULL;
--
-- which is correct for an empty database and fails on every database that has
-- a building in it. It is added nullable here and set NOT NULL in Section 3,
-- after the backfill has filled it. The END STATE is identical to what Prisma
-- asked for - a NOT NULL bigint with that foreign key - and the end state is
-- what the shadow-database diff compares. `migrate dev --create-only` still
-- reports an empty migration afterwards, and that is the check that this was
-- safe rather than merely plausible.
--
-- The same rule as add_bas_tables applies to the rest: Prisma models columns,
-- indexes and foreign keys. It does not model CHECK constraints, triggers or
-- views, so those are invisible to it in both directions and live here.
--
--   Section 1  The connection_mode CHECK constraint.
--   Section 2  The backfill. One project, one building, one station - the ones
--              that actually exist.
--   Section 3  bas_sites.project_id becomes NOT NULL.
--   Section 4  Two triggers keeping bas_sites.org_id and bas_projects.org_id
--              from disagreeing.
--   Section 5  bas_v_data_dictionary, replaced to EXCLUDE the credentials
--              table. Read that section before touching the predicate.
--   Section 6  COMMENT ON for the new objects.
--   Section 7  A defensive REVOKE on the credentials table.
-- =============================================================================


-- =============================================================================
-- SECTION 1 - CHECK constraint
--
-- The fourteenth in this schema. CHECK-over-text rather than a Postgres enum,
-- for the same reason as the thirteen in add_bas_tables: an enum column changes
-- how the collector's inserts bind their parameters, and decision D1 says the
-- collector changes only its connection string.
--
-- Deliberately the ONLY constraint on this column. Two coherence rules are NOT
-- enforced here:
--
--   * 'direct' does not require base_url
--   * 'via_parent' does not require parent_station_id
--
-- Both are tempting and both are wrong at this layer. A station discovered
-- behind a central collector and not yet configured has neither, and the
-- Settings tab has to be able to list it as "discovered, unassigned"
-- (docs/B7_settings_and_hierarchy_plan.md, Risks). A constraint that refused to
-- store that row would make the incomplete state unrepresentable instead of
-- visible. Those two rules belong in the B7.4 form validation.
-- =============================================================================

ALTER TABLE bas_stations
  ADD CONSTRAINT bas_stations_connection_mode_check
  CHECK (connection_mode IN ('direct','via_parent'));


-- =============================================================================
-- SECTION 2 - Backfill
--
-- Exactly one project, one building and one station, all of them things that
-- exist. No example rows, no "Liberty Center", no placeholder org.
--
-- This project has a standing rule against plausible-looking invented data:
-- Temp1-Temp3 are left unclassified because nobody knows what they represent,
-- and giving them a made-up role would make the AI answer confidently about
-- something untrue. A fake project row is the same mistake with a longer fuse -
-- it reaches a dropdown, and somebody believes it.
--
-- On a fresh database all of this is a no-op. That is the normal case for the
-- test database and for a first deployment, and it is why the block returns
-- early rather than inserting a project with no buildings under it.
-- =============================================================================

DO $backfill$
DECLARE
  orphan_orgs   bigint[];
  target_org    bigint;
  new_project   bigint;
  moved         integer;
BEGIN
  SELECT array_agg(DISTINCT org_id) INTO orphan_orgs
    FROM bas_sites WHERE project_id IS NULL;

  -- Fresh database: no buildings, so nothing to place and no project to invent.
  IF orphan_orgs IS NULL THEN
    RAISE NOTICE 'B7.1 backfill: no buildings to place, no project created.';
    RETURN;
  END IF;

  -- There is one org. If that is ever untrue, the right answer is a human
  -- naming each project, not this migration copying one name across all of
  -- them - which is precisely the invented-data failure described above.
  IF array_length(orphan_orgs, 1) > 1 THEN
    RAISE EXCEPTION
      'B7.1 backfill expected buildings under exactly one org, found % (org_ids %). '
      'Create the projects by hand and re-run - do not let this migration name them.',
      array_length(orphan_orgs, 1), orphan_orgs;
  END IF;

  target_org := orphan_orgs[1];

  INSERT INTO bas_projects (org_id, name, notes)
  VALUES (
    target_org,
    'Peck Hannaford + Briggs',
    'Created by the B7.1 backfill so the one existing building had a project to sit under. '
    'Not a placeholder - it is the real project name.'
  )
  RETURNING project_id INTO new_project;

  UPDATE bas_sites SET project_id = new_project WHERE project_id IS NULL;
  GET DIAGNOSTICS moved = ROW_COUNT;

  RAISE NOTICE 'B7.1 backfill: project % created under org %, % building(s) placed.',
    new_project, target_org, moved;
END
$backfill$;

-- Every station already carries a connection_mode - the column is NOT NULL with
-- a 'via_parent' default, so the ALTER above filled it. This corrects the ones
-- we actually reach ourselves.
--
-- Derived from what the rows say rather than from a station name typed in here.
-- A station with an oBIX base_url and no parent is, by definition, one that
-- nothing else is importing for us. Today that matches exactly one row,
-- SpringGroveLabComputer - whose name is NOT touched by this statement or any
-- other in this migration. It is case-sensitive and appears literally in every
-- oBIX URL.
--
-- base_url is not rewritten either. The stored value has no trailing slash and
-- the collector in phb-bas builds its URLs from it as it stands; "correcting"
-- that here would change a live string for cosmetics.
UPDATE bas_stations
   SET connection_mode = 'direct'
 WHERE base_url IS NOT NULL
   AND parent_station_id IS NULL;


-- =============================================================================
-- SECTION 3 - project_id becomes NOT NULL
--
-- Deferred from the generated ALTER at the top of this file so the backfill
-- could run first. After this the column is exactly what schema.prisma
-- declares, which is why the drift check comes back empty.
-- =============================================================================

ALTER TABLE bas_sites ALTER COLUMN project_id SET NOT NULL;


-- =============================================================================
-- SECTION 4 - bas_sites.org_id and bas_projects.org_id must agree
--
-- bas_sites now has both org_id and project_id, and bas_projects has org_id, so
-- the same fact is written in two places and nothing declarative stops them
-- diverging. A foreign key cannot express it and a CHECK cannot read another
-- table, so it is a trigger - which Prisma ignores, exactly like the
-- roll-horizon trigger in add_bas_tables.
--
-- org_id was NOT dropped from bas_sites instead, which would have removed the
-- redundancy outright: it is in the column list scripts/bas-tables.ts moves
-- from the standalone database, and that list is shared with the verifier.
--
-- Both directions are covered. Guarding only the bas_sites side would leave the
-- invariant half-true, which is worse than one you know you do not have: the
-- failure would surface as a building belonging to two different orgs depending
-- on which table you asked.
-- =============================================================================

CREATE FUNCTION bas_sites_project_org_match() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
  project_org bigint;
BEGIN
  -- A BEFORE ROW trigger runs before the column constraints AND before the
  -- foreign keys, so this function gets first refusal on rows whose real
  -- problem is neither of the things it exists to check. In both of those
  -- cases it must stand aside: PostgreSQL's own message names the actual
  -- fault, and anything raised here would replace it with a worse one.
  --
  -- This is not hypothetical. The first version checked org equality
  -- unconditionally, so an INSERT that simply omitted project_id - which is
  -- what the phb-bas collector's ensure_site() did - was refused with
  --
  --     bas_sites.org_id 5 does not match the org of project <NULL>
  --
  -- sending the reader to look for an org mismatch that did not exist. The
  -- missing column was the whole story.

  -- No project named: the NOT NULL constraint says so, precisely.
  IF NEW.project_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT org_id INTO project_org FROM bas_projects WHERE project_id = NEW.project_id;

  -- No such project: bas_sites_project_id_fkey says so, precisely.
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  -- Both rows exist and disagree. That is this trigger's actual job, and
  -- nothing else in the database would catch it.
  IF project_org <> NEW.org_id THEN
    RAISE EXCEPTION
      'bas_sites.org_id % does not match the org of project % (which is %)',
      NEW.org_id, NEW.project_id, project_org;
  END IF;

  RETURN NEW;
END;
$fn$;

COMMENT ON FUNCTION bas_sites_project_org_match() IS
  'Keeps bas_sites.org_id equal to the org of its project. bas_sites.org_id is redundant '
  'with bas_projects.org_id and is kept only because scripts/bas-tables.ts moves it; this '
  'is what stops the two disagreeing. Prisma does not model triggers and will not drop it.';

CREATE TRIGGER bas_sites_project_org_match
  BEFORE INSERT OR UPDATE OF org_id, project_id ON bas_sites
  FOR EACH ROW EXECUTE FUNCTION bas_sites_project_org_match();

CREATE FUNCTION bas_projects_org_match() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
  stranded bigint;
BEGIN
  SELECT site_id INTO stranded
    FROM bas_sites
   WHERE project_id = NEW.project_id
     AND org_id IS DISTINCT FROM NEW.org_id
   LIMIT 1;

  IF stranded IS NOT NULL THEN
    RAISE EXCEPTION
      'cannot move project % to org %: building % under it belongs to a different org',
      NEW.project_id, NEW.org_id, stranded;
  END IF;

  RETURN NEW;
END;
$fn$;

COMMENT ON FUNCTION bas_projects_org_match() IS
  'The other half of bas_sites_project_org_match: stops a project being moved to a '
  'different org while buildings still under it name the old one.';

CREATE TRIGGER bas_projects_org_match
  BEFORE UPDATE OF org_id ON bas_projects
  FOR EACH ROW EXECUTE FUNCTION bas_projects_org_match();


-- =============================================================================
-- SECTION 5 - bas_v_data_dictionary excludes bas_station_credentials
--
-- READ THIS BEFORE TOUCHING THE PREDICATE. It already carries one warning in
-- add_bas_tables about the two silent ways to get the schema filter wrong. This
-- is a third.
--
-- The view selects every object matching `bas\_%` and exists to be pasted into
-- an LLM prompt. bas_station_credentials matches that pattern. Left alone, the
-- structure of the credentials table - its existence, its column names, and the
-- fact that a password lives in it - goes into the prompt of the AI whose SQL
-- tool is explicitly supposed to be denied that table.
--
-- It leaks no password. It does not need to: telling a model there is a
-- password_ciphertext column is the first half of asking for it, and the whole
-- reason the credentials are a separate table rather than columns on
-- bas_stations is so that this layer can say no.
--
-- bas_projects IS included, deliberately. It is ordinary hierarchy metadata and
-- the AI cannot answer "compare the two buildings on that property" without it.
--
-- CREATE OR REPLACE rather than DROP and recreate: the column list is
-- unchanged, and nothing depends on this view.
-- =============================================================================

CREATE OR REPLACE VIEW bas_v_data_dictionary AS
SELECT
    c.relname AS object_name,
    CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' ELSE c.relkind::text END AS object_type,
    a.attname                            AS column_name,
    format_type(a.atttypid, a.atttypmod) AS data_type,
    NOT a.attnotnull                     AS is_nullable,
    col_description(c.oid, a.attnum)     AS column_description,
    obj_description(c.oid, 'pg_class')   AS object_description
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
WHERE n.nspname = 'public'
  AND c.relname LIKE 'bas\_%'
  AND c.relname <> 'bas_station_credentials'
  AND c.relkind IN ('r','v')
ORDER BY c.relkind DESC, c.relname, a.attnum;

COMMENT ON VIEW bas_v_data_dictionary IS
  'The entire annotated BAS schema in one query. Intended to be selected and pasted into an '
  'LLM prompt as context, so the model writes SQL against documented columns rather than '
  'guessing from names. Scoped to bas_-prefixed objects: the platform''s own employee and '
  'audit tables are deliberately NOT exposed here, and bas_station_credentials is excluded '
  'by name - it is the one bas_ object the model is not told about. Keep the COMMENT ON '
  'statements current - they are not decoration, they are the model''s only description of '
  'what the data means.';


-- =============================================================================
-- SECTION 6 - COMMENT ON for the new objects
--
-- Same rule as add_bas_comments: Prisma does not emit /// as COMMENT ON, so a
-- doc comment in schema.prisma reaches nobody reading the database. Every
-- object in bas_v_data_dictionary must carry a description or the model has to
-- guess from the name, and tests/bas-schema.test.ts fails a table that does
-- not.
--
-- bas_station_credentials is commented too, even though it is NOT in the
-- dictionary. Its audience is the person in psql at 2am, not the model.
--
-- ADJACENT STRING LITERALS, NOT ||. COMMENT ON ... IS takes a constant.
-- =============================================================================

COMMENT ON TABLE bas_projects IS
  'A property or campus - the level between an org and a building. A real table rather than '
  'a text label on bas_sites, because building and station are not 1:1 in either direction: '
  'one building can hold two JACEs in separate mechanical rooms, and one JACE can serve '
  'several small buildings on a strip.';

COMMENT ON COLUMN bas_projects.name IS
  'Unique within the org, not globally. Two customers may both have a "Main Campus".';

COMMENT ON TABLE bas_sites IS
  'A building. Belongs to exactly one project, which belongs to exactly one org. org_id is '
  'carried here as well as on the project and the two are kept in agreement by the '
  'bas_sites_project_org_match trigger - join through project_id, and treat org_id as a '
  'convenience rather than a second source of truth.';

COMMENT ON COLUMN bas_sites.project_id IS
  'The property this building sits on. Required. Building names are unique within the '
  'project, not within the org - two projects may each have a "North Building".';

COMMENT ON COLUMN bas_stations.connection_mode IS
  '''direct'' means the collector opens an oBIX connection to base_url itself. '
  '''via_parent'' means another station imports this one''s history over the NiagaraNetwork '
  'and we read it from there - see parent_station_id. via_parent is the default because it '
  'is the mode that takes no action: reaching every JACE directly would need obixDriver-rt '
  'installed and a commissioning firmware upgrade, with downtime, on each one. A via_parent '
  'row with no parent_station_id is a station that has been discovered but not yet '
  'configured, which is a real state and deliberately not rejected.';

COMMENT ON COLUMN bas_stations.base_url IS
  'The oBIX base URL. Meaningful only when connection_mode is ''direct'', ignored otherwise. '
  'Stored exactly as the collector expects it, trailing slash included or not - do not '
  'normalise it.';

COMMENT ON TABLE bas_station_credentials IS
  'The Niagara login the collector uses for one station. A SEPARATE TABLE ON PURPOSE, not '
  'columns on bas_stations: the bas_readonly_platform role used by Grafana, the MCP server '
  'and the AI''s SQL tool is granted table by table across bas\_%, and this is the one table '
  'it must be refused. It is also excluded by name from bas_v_data_dictionary. Passwords are '
  'AES-256-GCM ciphertext; the key lives in the environment and never in this database.';

COMMENT ON COLUMN bas_station_credentials.password_ciphertext IS
  'AES-256-GCM ciphertext, base64, with the nonce and auth tag carried inside the encoded '
  'value. NEVER returned by an API, never logged, never put in an audit payload.';

COMMENT ON COLUMN bas_station_credentials.key_version IS
  'Which BAS_CREDENTIAL_KEY encrypted the value. Exists so the key can be rotated without a '
  'flag day. No default: a guessed key_version produces a row nobody can decrypt, and '
  'nothing records what the right answer was.';

COMMENT ON COLUMN bas_station_credentials.updated_by IS
  'The employee who last set this credential, or NULL if the platform itself wrote it. The '
  'value is never recorded here - only who touched it.';


-- =============================================================================
-- SECTION 7 - a defensive REVOKE on the credentials table
--
-- Belt and braces, and NOT the real fix. The real fix is in the other repo.
--
-- setup_readonly_role_platform.sql (in bas-mcp, run by hand after any migration
-- that adds a bas_ object - see runbook.md) grants SELECT table by table across
-- everything matching `bas\_%`. bas_station_credentials matches. So the next
-- time anybody runs that script, bas_readonly_platform is handed read access to
-- the ciphertext table, and nothing in this repo can prevent it.
--
-- That script needs an explicit exclusion. Until it has one, this at least
-- means the table does not start out readable.
--
-- Guarded on the role existing: it is created by hand on the machines that have
-- Grafana, and a fresh database or CI has no such role. An unguarded REVOKE
-- would fail the migration there under ON_ERROR_STOP=1.
--
-- bas_collector is deliberately NOT revoked. Under D15 the collector reads its
-- own targets and credentials from this table.
-- =============================================================================

DO $revoke$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bas_readonly_platform') THEN
    EXECUTE 'REVOKE ALL ON TABLE bas_station_credentials FROM bas_readonly_platform';
    RAISE NOTICE 'Revoked bas_readonly_platform on bas_station_credentials.';
  END IF;
END
$revoke$;
