-- AlterTable
ALTER TABLE "bas_stations" ADD COLUMN     "display_name" TEXT,
ADD COLUMN     "tls_sha256" TEXT;


-- =============================================================================
-- Everything above this line was generated by the Prisma migration engine.
-- Everything below it was written by hand, because Prisma cannot express it.
--
--   Section 1  A CHECK on the fingerprint's shape.
--   Section 2  The lab station's fingerprint, backfilled.
--   Section 3  COMMENT ON for both columns.
-- =============================================================================


-- =============================================================================
-- SECTION 1 - the fingerprint is 64 hex characters or it is nothing
--
-- The fifteenth CHECK in this schema. Prisma models neither, which is what makes
-- appending it here safe.
--
-- Lowercase only, and no colons. A fingerprint is a number written in hex, so
-- case and separators carry no information - but two spellings of one value
-- compare unequal, and comparing is the only thing this column is for. The
-- service normalises on write; this is what makes the normalisation true rather
-- than merely usual.
--
-- NULL is allowed and is the honest state for a station nobody has recorded a
-- certificate for. It is emphatically NOT the same as "verification is off":
-- verification is off everywhere today, because using this value is collector
-- work in phb-bas that has not happened yet.
-- =============================================================================

ALTER TABLE bas_stations
  ADD CONSTRAINT bas_stations_tls_sha256_shape
  CHECK (tls_sha256 IS NULL OR tls_sha256 ~ '^[0-9a-f]{64}$');


-- =============================================================================
-- SECTION 2 - the lab station's certificate
--
-- Measured from the live station, not generated. The JACE at 196.1.1.213
-- presents a self-signed certificate, so chain validation cannot work and the
-- collector currently runs with verification disabled entirely - outstanding
-- for weeks. Pinning this is the correct answer for a self-signed cert.
--
-- Keyed on the station name AND the base URL. A fingerprint belongs to one
-- certificate on one host, so matching more loosely than that would be
-- inventing a claim about a machine nobody measured. This is the one place a
-- station name is written into a migration, and it is unavoidable for exactly
-- that reason.
--
-- No-op on a fresh database and on the test database, where the row is absent.
-- =============================================================================

DO $tls$
DECLARE
  updated integer;
BEGIN
  UPDATE bas_stations
     SET tls_sha256 = '483bc6d6cbefa12914398e7e27010b6275b287503ac19e0c783482278dc186b4'
   WHERE niagara_station_name = 'SpringGroveLabComputer'
     AND base_url = 'https://196.1.1.213'
     AND tls_sha256 IS NULL;

  GET DIAGNOSTICS updated = ROW_COUNT;
  RAISE NOTICE 'B7.4: recorded the TLS fingerprint for % station(s).', updated;
END
$tls$;


-- =============================================================================
-- SECTION 3 - COMMENT ON
--
-- Both columns are in bas_v_data_dictionary, so both need a description or the
-- model guesses from the name. tests/bas-schema.test.ts fails an object without
-- one.
-- =============================================================================

COMMENT ON COLUMN bas_stations.display_name IS
  'What a person calls this station. Free text, and NOT the identifier - niagara_station_name is '
  'what Niagara answers to. NULL means nobody has named it, and the UI falls back to the Niagara '
  'name rather than inventing a prettier version of it.';

COMMENT ON COLUMN bas_stations.tls_sha256 IS
  'SHA-256 of the station''s TLS certificate: 64 lowercase hex characters, no colons, enforced by '
  'bas_stations_tls_sha256_shape. The JACE presents a self-signed certificate, so ordinary chain '
  'validation cannot work and pinning this is the correct answer. RECORDING it is not the same as '
  'USING it: the collector in phb-bas still runs with verification off, and a value here does not '
  'mean any connection is verified. Normalised on write, unlike niagara_station_name and base_url, '
  'because hex case and colons carry no meaning and two spellings would defeat the comparison.';
