-- AlterTable
ALTER TABLE "module_grants" ADD COLUMN     "is_module_admin" BOOLEAN NOT NULL DEFAULT false;


-- =============================================================================
-- Everything above this line was generated by the Prisma migration engine.
-- Everything below it is a COMMENT ON, which Prisma does not emit from /// docs
-- and does not notice the absence of.
--
-- Administrative rights over ONE module. B7.2, and a deliberate reversal of the
-- "per-module admins: leave schema room, do not implement" line that stood in
-- docs/04-auth-and-permissions.md until 8 September 2026.
--
-- It is a column on the grant rather than a table of its own so that revoking
-- someone's module access revokes their module admin rights in the same
-- statement. A separate module_admins table would let a revoked employee keep
-- an orphaned admin row, and nothing in the system would notice.
--
-- DEFAULT false, so every grant that already exists stays exactly as
-- unprivileged as it was. Nobody gains anything by applying this migration -
-- which is the only acceptable behaviour for a migration that adds a
-- permission.
-- =============================================================================

COMMENT ON COLUMN module_grants.is_module_admin IS
  'Administrative rights over this ONE module - for bas, the Settings tab. Not is_platform_admin: '
  'a module admin cannot reach /admin, cannot grant anyone anything, and cannot disable an '
  'employee. Lives on the grant row so that revoking module access revokes admin rights with it. '
  'Nothing about this column is BAS-specific.';
